apiVersion: apps/v1
kind: Deployment
metadata:
  name: exam-deployment
  labels:
    app: exam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exam
  template:
    metadata:
      labels:
        app: exam
    spec:
      containers:
        - name: exam
          image: dattruong/exam:s5
          ports:
            - containerPort: 8085
          env:
            - name: SPRING_APPLICATION_NAME
              valueFrom:
                configMapKeyRef:
                  name: dattruong-configmap
                  key: EXAM_APPLICATION_NAME
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: dattruong-configmap
                  key: SPRING_CONFIG_IMPORT
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: dattruong-configmap
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
---
apiVersion: v1
kind: Service
metadata:
  name: exam
spec:
  selector:
    app: exam
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
