server:
  port: 8085

exams:
  message: "Welcome to exams services related local APIs"
  contactDetails:
    name: "dat truong - Developer"
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  instance:
    preferIpAddress: true
    instance-id: "${spring.application.name}:${random.value}"

  client:
    fetchRegistry: 'true'
    registerWithEureka: 'true'
    serviceUrl:
      defaultZone: http://localhost:8071/eureka/

endpoints:
  shutdown:
    enabled: true

info:
  app:
    name: "exams"
    description: "Exams Application"
    version: "1.0.0"
