server:
  port: 8083

exams:
  message: "Welcome to users services related local APIs"
  contactDetails:
    name: "dat truong - Developer"
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: 'true'
    registerWithEureka: 'true'
    serviceUrl:
      defaultZone: http://localhost:8071/eureka/

endpoints:
  shutdown:
    enabled: true

info:
  app:
    name: "user"
    description: "User Application"
    version: "1.0.0"
