spring:
  application:
    name: "exam"
  config:
    import: "optional:configserver:http://localhost:8888/"
  cloud:
    stream:
      bindings:
        sendCommunication-out-0:
          destination: send-communication
    kafka:
      binder:
        brokers:
          -localhost: 9092
    openfeign:
      circuitbreaker:
        enabled: true

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 200


management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    com:
      dattruong:
        exam: DEBUG